# Generated by Django 3.1.7 on 2021-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='curr_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
