# Generated by Django 3.1.7 on 2021-10-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_curr_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='curr_price',
        ),
    ]
